# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# copyfeatures.py
# Created on: 2020-01-14 15:26:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Well_String = "C:\\Users\\dstarr\\Documents\\ArcGIS\\Projects\\RICS\\RICS.gdb\\Well_String"
Well_String__2_ = "C:\\Users\\dstarr\\Documents\\ArcGIS\\Default.gdb\\Well_String"

# Process: Copy Features
arcpy.CopyFeatures_management(Well_String, Well_String__2_, "", "0", "0", "0")

